apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: ap-northeast-2
  version: "1.26"

vpc:
  id: vpc-05793a9bfe5f5bd92
  subnets:
    private:
      a:
        id: subnet-07c46bcd272de86dc
      b:
        id: subnet-03407126daeb6018b

managedNodeGroups:
  - instanceType: t3.small
    name: addon
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    privateNetworking: true
  - instanceType: t3.small
    name: app
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    privateNetworking: true


cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
